# Generated by Django 4.2.6 on 2024-02-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_alter_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='likePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=90)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
    ]
