# Generated by Django 4.2.6 on 2024-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_likes',
            field=models.IntegerField(default=0),
        ),
    ]
